command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"
env:
  - name: UC_CATALOG
    value: monte_carlo_sim
  - name: UC_SCHEMA
    value: hospital_data
  - name: MAS_ENDPOINT_NAME
    value: mas-97e7e569-endpoint
  - name: SQL_WAREHOUSE_ID
    value: 0cd7ea0fa4c57f0f
  - name: DASHBOARD_ID
    value: "01f136d736ae1ce7b649daca07537d64"
  - name: GENIE_SPACE_ID
    value: "01f1362a8359132d9a8645eed1fdc9c0"
  - name: SEED_DEMO_DATA
    value: "true"
